#!/bin/bash
SQS_QUEUE="sqs-fargate-queue"
NETWORK_NAME="localstack-shared-net"
set -x

echo $AWS_PROFILE $SQS_QUEUE $NETWORK_NAME

#make LocalStack available to the ecs container, see https://docs.localstack.cloud/references/network-troubleshooting/endpoint-url/#from-a-container-localstack-created
#docker network create $NETWORK_NAME
LAMBDA_DOCKER_NETWORK=$NETWORK_NAME DOCKER_FLAGS="--network $NETWORK_NAME" DEBUG=1 localstack start -d
#DEBUG=1 localstack start -d
# Instructions as via original README
docker build -t go-fargate .
cd cdk
npm i

cdklocal bootstrap
cdklocal deploy --profile ${AWS_PROFILE} --require-approval never
awslocal sqs list-queues
awslocal dynamodb list-tables

awslocal sqs send-message --queue $SQS_QUEUE --message-body '{"message": "hello world"}'

#localstack stop
